/**
 * Muvuku: An STK data collection framework
 *
 * Copyright 2011-2012 Medic Mobile, Inc. <hello@medicmobile.org>
 * All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL MEDIC MOBILE BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __CONFIG_TURBO__
#define __CONFIG_TURBO__

#define PROGRAM_NAME "Medic Simapp"
#define PROGRAM_VERSION "v1.2.0"
#define PROGRAM_COPYRIGHT "Copyright (c) 2011-2015 Medic Mobile, Inc."
#define PROGRAM_COPYRIGHT_EXTRA "Open source version: no warranty."
#define PROGRAM_RIGHTS "All Rights Reserved."

#define PROGRAM_DISTRIBUTION \
    "Redistribution in whole or part is permitted" \
    "under the terms of the GNU GPL, version three."

#undef DEBUG

#define CONFIG_LANG_EN
/* #define CONFIG_LANG_ES */
/* #define CONFIG_LANG_FR */
#define CONFIG_LANG_UN

#endif /* __CONFIG_TURBO__ */

